export const SET_PERSONAL_ITEMS = 'SET_PERSONAL_ITEMS';
export const SET_HEALTHY_ITEMS = 'SET_HEALTHY_ITEMS';
export const SET_FAST_FOOD_ITEMS = 'SET_FAST_FOOD_ITEMS';
export const SET_IS_LOADING = 'SET_IS_LOADING';
